FROM registry.redhat.io/rhel9/rhel-bootc:9.6
RUN dnf -y config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
    dnf -y install flightctl-agent-1.0.0 && \
    dnf clean all && \
    systemctl enable flightctl-agent && \
    systemctl mask bootc-fetch-apply-updates.timer
ADD domain.crt /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust
# Uncomment the following line to use early binding
# ADD config.yaml /etc/flightctl
