FROM registry.redhat.io/rhel9/rhel-bootc:9.6
RUN dnf -y config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
    dnf -y install flightctl-agent && \
    dnf clean all && \
    systemctl enable flightctl-agent && \
    systemctl mask bootc-fetch-apply-updates.timer
